platform:
  - x86
  - x64
environment:
  matrix:
    - RUST_VERSION: stable
      BUILD_TARGET: gnu
      RUBY_VERSION: 22
    - RUST_VERSION: stable
      BUILD_TARGET: gnu
      RUBY_VERSION: 23
cache:
  - target\debug\build
  - target\debug\deps
  - '%USERPROFILE%\.cargo'
install:
  - ps: |
        $env:PATH += ";C:\rust\bin";
        if ($env:platform -eq 'x86') {
          $env:RUBY_DIR = "Ruby${env:RUBY_VERSION}"
          $arch_expanded = "i686-pc-windows-${env:BUILD_TARGET}";
          $env:ARCH = "x86";
          $env:bits = "32";
        } else {
          $env:RUBY_DIR = "Ruby${env:RUBY_VERSION}-x64"
          $arch_expanded = "x86_64-pc-windows-${env:BUILD_TARGET}";
          $env:ARCH = "amd64";
          $env:bits ="64";
        }
        $env:PATH = "C:\${env:RUBY_DIR}\bin;${env:PATH}";
        if ($env:BUILD_TARGET -eq 'gnu') {
          $env:PATH += ";C:\msys64\mingw${env:bits}\bin";
          gcc --version;
        }
        if ($env:RUST_VERSION -eq 'stable') {
          echo "Downloading $channel channel manifest";
          $manifest = "${env:Temp}\channel-rust-stable";
          Start-FileDownload "https://static.rust-lang.org/dist/channel-rust-stable" -FileName "$manifest";

          # Search the manifest lines for the correct filename based on expanded arch
          $match = Get-Content "$manifest" | Select-String -pattern "${arch_expanded}.exe" -simplematch;
          if (!$match -or !$match.line) {
            throw "Could not find ${arch_expanded} in stable channel manifest";
          }

          $env:rust_installer = $match.line;
        } else {
          $env:rust_installer = "rust-${env:RUST_VERSION}-${arch_expanded}.exe";
        }
        $tag_suffix = echo "${env:APPVEYOR_REPO_TAG_NAME}" | Select-String -pattern "-rust$"
        if ($tag_suffix) {
          $env:RUST_TAG = "1";
        }
  - curl --show-error --location --retry 5 --output rust-installer.exe https://static.rust-lang.org/dist/%rust_installer%
  - .\rust-installer.exe /VERYSILENT /NORESTART /DIR="C:\rust"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - rustc -vV
  - cargo -vV
  - ruby --version
  - gem --version
  - bundle --version
  - bundle config --local path vendor/bundle
  - bundle install
build_script:
  - bundle exec rake thermite:tarball
test_script:
  - bundle exec rake test
  - ps: |
        if ($env:RUST_TAG -ne '1') {
          bundle exec rake install;
          gem uninstall rusty_blank;
          gem install minitest;
          gem install "pkg\*.gem";
          ruby "test\test_rusty_blank.rb";
        }
artifacts:
  - path: rusty_blank-*.tar.gz
deploy:
  - provider: GitHub
    artifact: /rusty_blank-.*\.tar\.gz/
    draft: false
    prerelease: false
    auth_token:
      secure: VUF+Nfn07Dym0IlQHG3NO6SdHMa1uG8IVzRY+beMUPR49b6M5mTvpPTm3OWO40G7
    on:
      appveyor_repo_tag: true
      RUST_TAG: 1
      RUBY_VERSION: 23
