[package]
name = "rusty_blank"
version = "0.1.2"
authors = ["Mark Lee"]

[lib]
crate-type = ["dylib"]

[features]

lint = ["clippy"]

[dependencies]

ruru = "0.6"

clippy = { version = "*", optional = true }
