[package]
name = "rusty_blank"
version = "0.1.5"
authors = ["Mark Lee"]

[lib]
crate-type = ["dylib"]

[dependencies]

ruru = { git = "https://github.com/malept/ruru", branch = "windows-compatible" }
