[package]
name = "rusty_blank"
version = "0.1.5"
authors = ["Mark Lee"]
repository = "https://github.com/malept/rusty_blank"

[lib]
crate-type = ["dylib"]

[dependencies]

ruru = { git = "https://github.com/malept/ruru", branch = "windows-compatible" }
